services:
  - type: web
    name: tg-cloud-backend
    runtime: python
    env: python
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_UPLOAD_MODE
        sync: false
      - key: API_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TG_CHAT_ID
        sync: false
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_SESSION_STRING
        sync: false
      - key: UPLOAD_TIMEOUT_SECONDS
        sync: false
      - key: TELEGRAM_HTTP_TIMEOUT_SECONDS
        sync: false
      - key: BASE_URL
        sync: false
  buildCommand: pip install -r backend/requirements.txt
  startCommand: sh -lc "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
